### PR TITLE
Added post for jekyll-plus-materialize theme

### PR DESCRIPTION
**Pull request by enterthecrucible**

### CODE REVIEW

**Comment by geraldb** [comment]
@enterthecrucible  While you're waiting to get accepted on jekyllthemes.org  - I invite you to send a push request to the alternative [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/drjekyllthemes.github.io) directory. Same system. Just a little simple, easier. Your theme is welcome. Cheers.

**Comment by geraldb** [comment]
@enterthecrucible   A friendly reminder - you're invited to add your jekyll-plus-materialize theme to the [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/themes) directory - all new themes added will get spotlighted in the [Dr. Jekyll's Themes of Month Series](https://talk.jekyllrb.com/t/dr-jekylls-themes-of-the-month-july-2015-edition-hola-alfa-personal-clean-dark/1023), for example. Cheers.

**Comment by mattvh** [comment]
Thumbnail must have exact dimension of 250x200, as outlined in the submission instructions. Please resubmit with the appropriate thumbnail.

**Comment by gynter** [comment]
I listed Your theme in PR #181 with correct image. No need to make new PR by You.

**Pull request closed without merging**
