### PR TITLE
Add new theme: clyell

### PR DESCRIPTION
**Pull request by gildasio**
Fix #490

### CODE REVIEW

**Comment by artlogic** [comment]
You might consider updating the readme link to actually link to the readme. Otherwise it looks good!

**Comment by gildasio** [comment]
@artlogic to the file (https://github.com/gildasio/clyell/blob/gh-pages/README.md) or a section (https://github.com/gildasio/clyell#clyell)?

**Comment by artlogic** [comment]
@gildasio your choice

**Comment by gildasio** [comment]
@artlogic done

**Pull request merged**
