### PR TITLE
New jekyll Theme - Atlas

### PR DESCRIPTION
**Pull request by NrdyBhu1**
A new jekyll theme atlas.
This is a minimal theme.

### CODE REVIEW

**Comment by mattvh** [comment]
Theme submissions must have a thumbnail that is exactly 250x200 pixels, not larger. Also, please do not place additional screenshots within the thumbnails directory. This would be mergeable if both of those issues are corrected.

**Comment by NrdyBhu1** [comment]
ok, will do! :+1:

**Comment by NrdyBhu1** [comment]
@mattvh changes done, only two screenshot are present, because when they are scaled to 250x200 the image is not visible, so for screenshot I put another one. Is it ok or should I not keep that also?

**Comment by mattvh** [comment]
I'd prefer to avoid the second image being in the thumbnails directory. I try not to host full screenshots to keep the repo size down. What most people who include them seem to do, is they host a screenshot in their own repository (for their README or whatever) and just link to that. Example: http://jekyllthemes.org/themes/what-a-theme/

The thumbnail size change looks good other than that.

**Comment by NrdyBhu1** [comment]
oh, that's genius, I'll do the same

**Comment by NrdyBhu1** [comment]
Checked everything, looks good waiting for accepting the pr

**Comment by NrdyBhu1** [comment]
Checked everything, looks good, waiting for accepting the pr
Screenshot from 2021-06-30 14-18-01

**Pull request merged**
