### PR TITLE
Added "BlogInn" bold theme for Jekyll

### PR DESCRIPTION
**Pull request by TomasBankauskas**

### CODE REVIEW

**Comment by gynter** [comment]
This is not a free template.

**Comment by redwallhp** [comment]
Chiming in here: Jekyll Themes, thus far, is entirely a free repository, so this isn't really an appropriate submission.

Whether paid themes should be allowed at all is a question that I think could *potentially* use community input, but at the very least they'd have to be isolated and displayed separately from the main collection. I particularly feel strongly about that, as browsing for "free" themes and running into paywalls is not a pleasant experience for anybody.

**Comment by mattvh** [comment]
Chiming in here: Jekyll Themes, thus far, is entirely a free repository, so this isn't really an appropriate submission.

Whether paid themes should be allowed at all is a question that I think could potentially use community input, but at the very least they'd have to be isolated and displayed separately from the main collection. I particularly feel strongly about that, as browsing for "free" themes and running into paywalls is not a pleasant experience for anybody.

**Comment by gynter** [comment]
Sorry, I was afk a bit therefore wasn't able to merge things. I personally think that adding premium themes is not a good idea. Besides, there's already http://www.jekyllthemes.io/ which has premium themes, including the one mentioned in this PR.

**Comment by mattvh** [comment]
No worries, I've had my own problems with not finding time to contribute here in recent months. But yeah, I feel like premium themes are already curated enough by the places that sell them.

**Pull request closed without merging**
