### PR TITLE
Adding Strata-Jekyll

### PR DESCRIPTION
**Pull request by DavidForster**
Adding another port of "Strata" by HTML5UP

### CODE REVIEW

**Comment by gynter** [comment]
Hello and thanks for the PR!

Is this the same [Strata theme](http://jekyllthemes.org/themes/strata/) which is already added from [CloudCannon port](https://github.com/CloudCannon/Strata-Jekyll-Theme)? If yes, then I'd rather avoid duplicates.

**Comment by DavidForster** [comment]
Hey @gynter,

It's the same basic design as the one from CloudCannon. Strata is a design from HTML5UP.net and CloudCannon added some basic logic to it but IMO it is not usable as a theme (for example, they just list out ALL posts on the homepage). That is why I created my version, which (IMO) has significantly better and more functionality.

I understand if you do not want to add it based purely on the design.

**Comment by gynter** [comment]
Currently I'm noticing some indifferences between Your port and the original HTML5UP template (for example, the left panel background image is way more blurred out - [original](http://i.imgur.com/tvcaiSw.png), [Your version](http://i.imgur.com/ibjT6ny.png), [CloudCannon's version](http://i.imgur.com/dxClgJy.png)).

As for the post listing (pagination) I completely agree with You. My suggestion is that You'd implement the pagination support to CloudClannons port of the Strata (in the [index.html](https://github.com/CloudCannon/Strata-Jekyll-Theme/blob/master/index.html) file here). I'm sure that @mneumegen would happily accept Your pull request.

**Comment by DavidForster** [comment]
The images are different. If you copy the [demo](http://html5up.net/uploads/demos/strata/) of Strata then you copy the images from [Unsplash](unsplash). If you download the [distribution](http://html5up.net/strata/download) then you will see that the designer has intentionally blurred the background image as I expect it is intended that you replace it with your own. This is also indicated by the line in the footer of the demo: "Demo Images: Unsplash", which does not appear in the distribution. Of course, Unsplash images are free to distribute, but that is not my choice.

Never mind. I figured there might be some kind of issue with two different ports of the same design. Feel free to close this PR.

**Comment by gynter** [comment]
If it's slightly different then maybe rename it to something like Strata Legacy or Strata NG to avoid confusion?

**Pull request closed without merging**
