### PR TITLE
Add Jekyll-Video

### PR DESCRIPTION
**Pull request by mushishi78**

### CODE REVIEW

**Comment by geraldb** [comment]
@mushishi78 While you're waiting to get accepted on jekyllthemes.org - I invite you to send a pull request to the alternative [Dr. Jekyll's Themes](http://drjekyllthemes.github.io) directory. Same system. Just a little simpler, easier. Your Jekyll Video theme is welcome. Cheers.

**Comment by mushishi78** [comment]
@geraldb I created a PR for you, but I'd totally disagree with the claim that it's "a little simpler, easier". It's confusing. I'll add some issues to explain why.

**Comment by geraldb** [comment]
@mushishi78  Sorry for the confusion. The o/ folder will get deleted (it's short for output, that is, auto-generated output). Thanks again for your great theme and your comments. Cheers.

**Comment by gynter** [comment]
Hello and thanks for the PR.

Please add time to `date` in the front matter. If You don't know the correct time, then set it as `00:00:00`.

**Comment by mushishi78** [comment]
I set the time to 00:00:00 and squash the commits.

**Comment by gynter** [comment]
Thank You, everything seems to be fine now! @mattvh :shipit:

**Pull request merged**
