### PR TITLE
add Jekyll Theme Simple Blog by lorepirri

### PR DESCRIPTION
**Pull request by lorepirri**
new theme added

### CODE REVIEW

**Comment by junlulocky** [comment]
Hey @lorepirri , I think your old submission: https://pages-themes.github.io/cayman/
is similar to this one right?

**Comment by junlulocky** [comment]
I mean this one: https://lorepirri.github.io/cayman-blog/

**Comment by lorepirri** [comment]
Hi @junlulocky , 

Thanks for going through my submission.

I wanted to leave the cayman-blog as much as possible close to cayman theme and keep it in sync with it.

Simple Blog Theme has way more features and changed too much from its upstream, so I created a new theme.

New Features:
 +- Multi-language
 +- SEO optimized for Facebook preview
 +- Facebook plugins integration (Page, Comments, Messenger, Like)
 +- Facebook Mirroring Comments
 +- Social buttons (facebook, instagram, linkedin, twitter, github, gitlab)
 +- RSS feed multi-language

you can have a look at the two demos:
https://lorepirri.github.io/cayman-blog/
https://lorepirri.gitlab.io/jekyll-theme-simple-blog/

**Comment by junlulocky** [comment]
OK, sounds good!

**Comment by lorepirri** [comment]
thanks!

**Pull request merged**
