### PR TITLE
Review all themes and fix errors

### LINKED ISSUE #135: Template swift without demo
It has a broken link http://pranav.maangalabs.com/

### PR DESCRIPTION
**Pull request by gynter**
- Update .gitignore and _config.yml;
- Fix links, formatting, and content errors;
- Fix preview image thumbnails;
- Remove broken links;
- Rename files with wrong dates in filename;
- Rename preview image thumbnails to similar naming format;
- Fixes #135, #139, #140, #141, #142, #143, #144, #145, #146, #147,
  #151, #160, #161, and #163.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This is awesome! You've put a lot of effort in here. 

It would be awesome if @mattvh could make you a contributor, then you can merge PRs rather than everyone having to wait for long periods of time. You're dedicated and have definitely earned it!

**Comment by rohanchandra** [comment]
@gynter Could you keep the Type Theme homepage link as-is. The current homepage provides greater detail about the theme's features and installation.

**Comment by gynter** [comment]
@rohanchandra my bad, it seems I made a mistake there because for some themes the homepage and demo were exactly same link so I replaced homepage with respective Github link. Reading nearly 100 files in one night made my eyes :fire: . Fixed now, updated the PR also.

**Comment by gynter** [comment]
@mattvh ping

**Comment by mattvh** [comment]
Wow, this is quite a commit. I'll work on getting it merged shortly. (Sorry for the delay. I've been busy with other projects, and life and stuff.)

As for bringing on a contributor, it's something I'm definitely interested in, though I'll have to fix up my deployment scripts and possibly move to using web hooks or something instead of manually pushing, to streamline the process a bit. I just haven't given it the full consideration required yet.

**Comment by jacobtomlinson** [comment]
@mattvh Is there any reason why you can't host this as a GitHub pages site rather than a separate server? Just CNAME your domain to it?

**Pull request merged**
