### PR TITLE
Added Bulma Clean Theme

### PR DESCRIPTION
**Pull request by chrisrhymes**

### CODE REVIEW

**Comment by artlogic** [comment]
Please update the image to be exactly 250x200. Thanks!

**Comment by chrisrhymes** [comment]
@artlogic I've updated the thumbnail size as requested

**Comment by artlogic** [comment]
Thanks - one other problem: the license link doesn't work. Looks like it needs a .txt. Please fix it up and I'll merge.

**Comment by chrisrhymes** [comment]
I've now updated the licence link. Thanks.

**Pull request merged**
