### PR TITLE
Added Event Jekyll Theme

### PR DESCRIPTION
**Pull request by melvinchng**

### CODE REVIEW

**Comment by junlulocky** [comment]
My opinion is that we already have similar one page theme, e.g. https://jarrekk.github.io/Jalpc/. 
How about you @jarrekk, @mattvh, @InsidiousMind, @gynter ?

**Comment by melvinchng** [comment]
@junlulocky , This is not a one page theme. More like a package.

**Comment by InsidiousMind** [comment]
Personally i disagree. I think they are only similar in organization, but in terms of design they are sufficiently different.

**Comment by jarrekk** [comment]
@junlulocky @InsidiousMind @melvinchng I think they are different styles and designs in jekyll.

**Comment by InsidiousMind** [comment]
according to @mattvh we should leave subjective opinion out of this. 

I say we wait for him to give feedback before we do anything.

**Comment by gynter** [comment]
I personally consider this as an original based on Agency, as stated by the author. @melvinchng Could You please point out the main differences with [Agency](http://jekyllthemes.org/themes/agency/) and maybe add those to the posts' description too? Then users could have reference points for comparison.

**Comment by mattvh** [comment]
Looks fairly different to me. If it weren't pointed out on the GitHub page that the index was derived from Agency, it probably would have slipped right under the radar. I might suggest adding more to the theme description though.

**Comment by melvinchng** [comment]
@gynter Just make sure I understand correctly. You mean I should fill up those markdown in for _posts, right? And I should add more information on how it stands out from the readme file?

**Pull request merged**
