### PR TITLE
Added Jekyll Bulma theme

### PR DESCRIPTION
**Pull request by erayaydin**

### CODE REVIEW

**Comment by jarrekk** [comment]
Hi, since we haven't seen this repository's owner for a very long time, I forked it to my [repo](https://github.com/jarrekk/jekyll-theme) and built this website with a new **domain name**:
 <http://jekylltheme.org>.

Anyone's theme who submitted it before will still be seen at <http://jekylltheme.org> and welcome everyone to contribute this website if you have nice themes.

Later I will beautify this repository to make it better, an excellent website needs everyone's contribution/PR too!😊

**Comment by erayaydin** [comment]
Thanks for auto submitting themes :+1:

**Comment by erayaydin** [comment]
If there is a problem with submitting this theme to new repo, I can also submit PR to new repo.

**Comment by jarrekk** [comment]
@erayaydin You can make a PR to new [repo](https://github.com/jarrekk/jekyll-theme).

**Pull request merged**
