### PR TITLE
Add new Kactus theme

### PR DESCRIPTION
**Pull request by nickbalestra**
- [x] Create a new post in the _posts directory and fill out the relevant YAML fields
- [x] Make a 250x200 thumbnail and drop it in the thumbnails directory. List its filename in the post's markdown file
- [x] Test it out, then push your changes up and open a pull request

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Wow I love your theme!

Just FYI this repo seems to have died, there is a fork of it which you probably want to make your PR on. https://github.com/ariestiyansyah/jekyllthemes

**Comment by nickbalestra** [comment]
Hey @jacobtomlinson happy you like it and thanks for the link to the fork. I gave it a look but as it stand atm I don't see much activity there either. 

@mattvh do you need any help with the merging of PR process? Let me know in case I will be more then happy to help.

**Comment by jacobtomlinson** [comment]
Haha don't be deceived. We'll have the new website up this week. We were waiting on a response from the core Jekyll maintainers about which domain name to use. 

We have been trying to get a response from @mattvh for weeks with no luck.

**Comment by jacobtomlinson** [comment]
See #118

**Comment by nickbalestra** [comment]
Thanks for the updates @jacobtomlinson! Keep me posted, definitely going to PR there once you'll the have the site online and running, good initiative, keep it up!

**Comment by mattvh** [comment]
Repo's not dead. I just haven't gotten around to merging things lately. Been busy with other things, then I was sick for three weeks. Should be just about caught up now.

**Pull request merged**
