### PR TITLE
Share wu-kan.github.io

### PR DESCRIPTION
**Pull request by wu-kan**

### CODE REVIEW

**Comment by artlogic** [comment]
@mattvh wondering if you are okay with merging themes with non-English descriptions?

**Comment by wu-kan** [comment]
> @mattvh wondering if you are okay with merging themes with non-English descriptions?

umm…ok😓

**Comment by artlogic** [comment]
@wu-kan I'm not saying I won't merge the theme, just asking if @mattvh would prefer a change before merging it.

**Comment by wu-kan** [comment]
@artlogic Sorry…I misunderstood😓

**Comment by artlogic** [comment]
@wu-kan no worries!

**Comment by artlogic** [comment]
@mattvh bump

**Comment by mattvh** [comment]
I've noticed there are one or two odd ones that are non-English in already, but I think it's best to stick to English going forward.

**Comment by artlogic** [comment]
@wu-kan if possible can you please write/translate and English description? Thanks.

**Comment by wu-kan** [comment]
@artlogic okey🤓

**Comment by wu-kan** [comment]
@artlogic I made a new pull request [#662](https://github.com/mattvh/jekyllthemes/pull/662
). thx!

**Pull request closed without merging**
