### PR TITLE
Add Holo Alfa theme

### PR DESCRIPTION
**Pull request by steinvc**
First pull request. Tell me if I screwed up!

### CODE REVIEW

**Comment by Phlow** [comment]
Hey @steinvc , I took a look at your theme and if I click on `archive` and than on a post, I get a 404...

**Comment by steinvc** [comment]
@Phlow Thanks, fixed it.

**Comment by geraldb** [comment]
@steinvc   While you're waiting to get accepted on jekyllthemes.org  - I invite you to send a pull request to the alternative [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/themes) directory. Same system. Just a little simpler, easier. Your Holo Alfa theme is welcome. Cheers.

**Comment by steinvc** [comment]
@geraldb Already did that...

**Comment by geraldb** [comment]
@steinvc Sorry. Thanks again. Merged. Great theme. Cheers.

**Pull request merged**
