### PR TITLE
Fixing broken instructions on leonids. Adding links and missing instr…

### PR DESCRIPTION
**Pull request by MandyMeindersma**
…uctions

### CODE REVIEW

**Comment by MandyMeindersma** [comment]
@mattvh did you want to look this over? :)

**Comment by artlogic** [comment]
The addition of `bundle` makes good sense, but I don't quite understand changing the clone command to download links that point back to the published page. Why not just update the clone URL?

**Comment by MandyMeindersma** [comment]
@artlogic That repo is archived and does not exist anymore. The only way to get the files is to directly download? Unless I am missing something?

**Comment by artlogic** [comment]
I think it's just a typo in the clone command. I think this'll work: `git clone https://github.com/renyuanz/leonids.git`

**Comment by MandyMeindersma** [comment]
lol, you are right :P I'll make that change and then push

**Pull request merged**
