### PR TITLE
Add Jekyll-MDL Theme

### PR DESCRIPTION
**Pull request by oscarmcm**
- [x] Create a new post in the _posts directory and fill out the relevant YAML fields
- [x] Make a 250x200 thumbnail and drop it in the thumbnails directory. List its filename in the post's markdown file
- [x] Test it out, then push your changes up and open a pull request

### CODE REVIEW

**Comment by geraldb** [comment]
@oscarmcm  While you're waiting to get accepted on jekyllthemes.org - I invite you to send a pull request to the alternative [Dr. Jekyll's Themes directory](https://github.com/drjekyllthemes/themes). Same system. Just a little simpler, easier. Your theme is welcome. Cheers.

**Comment by geraldb** [comment]
@oscarmcm  @dubuyuye  A friendly reminder - you're invited to add your Jekyll-MDL theme to the [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/themes) directory - all new themes added will get spotlighted in the [Dr. Jekyll's Themes of Month Series](https://talk.jekyllrb.com/t/dr-jekylls-themes-of-the-month-july-2015-edition-hola-alfa-personal-clean-dark/1023), for example. Cheers.

**Comment by oscarmcm** [comment]
@geraldb done :smiley:

**Comment by geraldb** [comment]
@oscarmcm  Gracias. Thanks. Cheers. Saludos.

**Pull request merged**
