### PR TITLE
Add jekyl-theme-minimal-resume

### PR DESCRIPTION
**Pull request by murraco**
## Description

This is a simple Jekyll theme for a minimal resume website: https://jekyll-theme-minimal-resume.netlify.com/.

### CODE REVIEW

**Comment by murraco** [comment]
cc @artlogic @mattvh

**Comment by artlogic** [comment]
@murraco Can you please include the hydrogen theme fix in a separate PR and remove it from this one?

**Comment by murraco** [comment]
cc @artlogic done, once this is merged I'll create a new PR for the hydrogen fix :)

**Comment by murraco** [comment]
cc @artlogic @mattvh

**Comment by artlogic** [comment]
The thumbnail link appears to be incorrect. Can you fix?

Also, it might be nice to have at least a sentence or two describing the theme.

**Comment by murraco** [comment]
cc @artlogic I added a detailed description and fix the thumbnail link, let me know what you think

**Pull request merged**
