### PR TITLE
add Docster theme

### PR DESCRIPTION
**Pull request by DigitalMindCH**
Including our documentation theme docster

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Gorgeous! Your background image is a little odd though, very pixelated and has a lot of compression artefacts.

Background Image

**Comment by DigitalMindCH** [comment]
Hi Jacob

Thanks for pointing that out, seems like I saved it with the wrong Photoshop settings. Went ahead and changed it up now.

**Comment by jacobtomlinson** [comment]
No problem. I really like this theme!

**Comment by geraldb** [comment]
@DigitalMindCH   While you're waiting to get accepted on jekyllthemes.org  - I invite you to send a push request to the alternative [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/drjekyllthemes.github.io) directory. Same system. Just a little simpler, easier. Your theme is welcome. Cheers.

**Comment by geraldb** [comment]
@DigitalMindCH A friendly reminder - you're invited to add your Docster theme to the [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/themes) directory - all new themes added will get spotlighted in the [Dr. Jekyll's Themes of Month Series](https://talk.jekyllrb.com/t/dr-jekylls-themes-of-the-month-july-2015-edition-hola-alfa-personal-clean-dark/1023), for example. Cheers.

**Pull request merged**
