### PR TITLE
Add limpid theme

### PR DESCRIPTION
**Pull request by pranavrajs**
Added limpid theme

### CODE REVIEW

**Comment by gynter** [comment]
Hello! Please change thumbnail size to 250x200 px. Thanks!

**Comment by pranavrajs** [comment]
@gynter It's already 250*250. Please check.

**Comment by pranavrajs** [comment]
Oops! Sorry, will update the thumbnail.

**Comment by pranavrajs** [comment]
@gynter Updated now. Thanks

**Pull request merged**
