### PR TITLE
Renyuanz/master

### PR DESCRIPTION
**Pull request by renyuanz**
add leonids theme

### CODE REVIEW

**Comment by gynter** [comment]
The screenshot size must be 250 x 200 px.

**Comment by geraldb** [comment]
@renyuanz While you're waiting to get accepted on jekyllthemes.org - I invite you to send a pull request to the alternative [Dr. Jekyll's Themes](http://drjekyllthemes.github.io) directory. Same system. Just a little simpler, easier. Your Leonids theme is welcome. Cheers.

**Comment by renyuanz** [comment]
@gynter thanks for point that out, it fixed now.
@geraldb I just send a pr to your directory.
Cheers.

**Comment by gynter** [comment]
@mattvh :shipit:

**Pull request merged**
