### PR TITLE
theme tiffany

### PR DESCRIPTION
**Pull request by dubuyuye**
a new theme named tiffany

### CODE REVIEW

**Comment by geraldb** [comment]
@dubuyuye   While you're waiting to get accepted on jekyllthemes.org  - I invite you to send a pull request to the alternative [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/themes) directory. Same system. Just a little simpler, easier. Your theme is welcome. Cheers.

**Comment by geraldb** [comment]
@dubuyuye  A friendly reminder - you're invited to add your theme to the [Dr. Jekyll's Themes](https://github.com/drjekyllthemes/themes) directory - all new themes added will get spotlighted in the [Dr. Jekyll's Themes of Month Series](https://talk.jekyllrb.com/t/dr-jekylls-themes-of-the-month-july-2015-edition-hola-alfa-personal-clean-dark/1023), for example. Cheers.

**Comment by dubuyuye** [comment]
@geraldb 

Already did that

**Comment by geraldb** [comment]
@dubuyuye  Great. Thanks. Cheers. Enjoy the summer.

**Pull request merged**
