### PR TITLE
domain changed

### PR DESCRIPTION
**Pull request by bit-ranger**
Domain name changed, the old demo cannot be reached now.

### CODE REVIEW

**Comment by gynter** [comment]
Hello! Pease change thumbnail size to 250x200 px. Thanks!

**Comment by WakelessDragon** [comment]
@gynter 
Hello, the thumbnail size was already changed. Thanks!

**Comment by gynter** [comment]
Current thumbnail size is 936px × 749px but it should be 250x200 px.

**Comment by WakelessDragon** [comment]
Current thumbnail is 250 × 200 px now.

**Pull request closed without merging**
