### PR TITLE
{ Personal } Jekyll Theme

### PR DESCRIPTION
**Pull request by PanosSakkos**
Added { Personal } Jekyll theme.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Just to let you know you don't have to close and open a new PR every time you push commits. The PR will update automatically with your changes.

**Comment by PanosSakkos** [comment]
Ah, didn't know that. Thanks! :)

**Comment by jacobtomlinson** [comment]
No problem :+1:

**Comment by gynter** [comment]
@PanosSakkos I recommend squashing those 11 commits into one so it won't clobber up the changelog.

**Comment by jacobtomlinson** [comment]
Agreed!

**Comment by PanosSakkos** [comment]
@gynter Makes sense. If I squash my branch and push to the origin, will the PR here get messy? Should I close this and open a new one?

Thanks!
:panos

**Pull request closed without merging**
